name: Build ESP examples

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Install ldproxy
        run: cargo install ldproxy
      - name: Install espup
        run: cargo install espup
      - name: Install esp toolchain
        run: espup install
      - name: Build esp32c3_ble
        working-directory: ./examples/use_rust/esp32c3_ble
        run: cargo +esp build --release
      - name: Build esp32c3_ble with config
        working-directory: ./examples/use_config/esp32c3_ble
        run: cargo +esp build --release
      - name: Build esp32c6_ble
        working-directory: ./examples/use_rust/esp32c6_ble
        run: cargo build --release
      - name: Build esp32c6_ble with config
        working-directory: ./examples/use_config/esp32c6_ble
        run: cargo build --release
      - name: Build esp32s3_ble
        working-directory: ./examples/use_rust/esp32s3_ble
        run: cargo +esp build --release
      - name: Build esp32s3_ble with config
        working-directory: ./examples/use_config/esp32s3_ble
        run: cargo +esp build --release
